### ISSUE TITLE
Initialize DialogueRunner.cs on Awake

### ISSUE THREAD

**Issue by Mortup** [YarnSpinnerTool/YarnSpinner-Unity#180]
**Is your feature request related to a problem? Please describe.**
There's a race condition when trying to use Yarn on Start() because there's no way to know if DialogueRunner.cs will start first.

**Describe the solution you'd like**
Moving DialogueRunner.cs initialization to Awake instead of Start should solve the issue.

**Describe alternatives you've considered**
I tried using Unity custom Script Execution Order, but that only works to establish an order for Awake and Update, not for Start.

**Additional context**
![image](https://user-images.githubusercontent.com/26821059/167072760-feb04597-0741-4415-8c51-80fadc14ae46.png)

The changes are simple enough that I can upload a PR if that helps. I already modified the script on my own project and seems to work fine, but you probably know better than me if there's any potential problems with this approach.

**Comment by McJones** [comment]
fixed in 0d3916269ce9542c5e52774af530db581758dabe

**Comment by fmoo** [comment]
fwiw, this causes problems for folks who use AddComponent<> and pool DialogueRunners, since Awake() runs before returning control of execution to the AddComponent caller.   As a result we get unhandled exceptions when Awake attempts to check the Count of (and iterate on) `dialogueViews`. 

I fixed this on top of my fork with all my random junk: https://github.com/fmoo/YarnSpinner-Unity/commit/ae2746d8b4946e7ef484062149aa4fe0e267d28b, but I'll probably also remove the warning as well, since there's no way to avoid it in this model.

Perhaps the warning should be moved back to Start() as there is no opportunity to turn down verboseLogging before then?
