### ISSUE TITLE
Duplicated localization key using new Unity Localization system

### ISSUE THREAD

**Issue by risingpixeldev** [YarnSpinnerTool/YarnSpinner-Unity#206]
**What is the current behavior?**

First of all thanks for all your work 👏 
I'm testing the new Unity Localization system and I found a bug. When adding a new text line to the script, a new key is added to the Localization Table. If the button "Add Line Tags to Scripts" is pressed after, a duplicated key is added to the Localization Table.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:

Demonstration video here: [https://drive.google.com/file/d/1APcePa8yRZ-kFtDwdLflKhOkNy04qq7T/view?usp=sharing](https://drive.google.com/file/d/1APcePa8yRZ-kFtDwdLflKhOkNy04qq7T/view?usp=sharing)

**What is the expected behavior?**

The old key should be replaced by the new one.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.2.2
  - Unity Version: 2021.3.5f1

**Other information**

**Comment by samanabo** [comment]
I also have this issue. 
I followed the same steps you have in your video, and I got the extra entry.
I also go a number of additional entries that seem to be in error with values like `<dedent from 4>===` and `---`

**Comment by desplesda** [comment]
The issue relating to spurious `<dedent from 4>===` messages is an unrelated issue in the Yarn Spinner compiler, and is separately tracked in https://github.com/YarnSpinnerTool/YarnSpinner-Unity/issues/215.

The issue that's happening here is that lines that have no line ID get a system-assigned ID created for them, and then are added to the table. However, when Add Line Tags is used, those lines now get a _different_ line ID, and the string table doesn't know to remove the old one.

I've created a patch (attached) that deletes line entries that do not appear in the most recent compilation, but I haven't merged it because this would create problems when multiple Yarn Projects refer to the _same_ string table - if lines that aren't present in the current compilation are deleted, then Project A would delete Project B's lines every time it reimports, and vice versa. A proper solution will have to take into account the source of the project, or could potentially involve a check to see if an existing entry has a key that _would_ have been generated had it not been given an explicit line ID.

[206-Delete-Missing-Line-IDs.patch](https://github.com/YarnSpinnerTool/YarnSpinner-Unity/files/11944502/206-Delete-Missing-Line-IDs.patch)

**Comment by desplesda** [comment]
Currently, our thinking for a fix for this is:

- Find all Yarn Projects in the Unity project that use the selected string table.
- Compile them, and get the string table for each one. Merge these.
- Take the string table, and find all entries that have the Yarn line metadata object. These represent Yarn lines.
- Delete any line from the string table whose line ID is not found in the combined string table.
