### ISSUE TITLE
Variables updated in memory storage during runtime aren't updated in dialogue (2.0.0-beta4)

### ISSUE THREAD

**Issue by Creator13** [YarnSpinnerTool/YarnSpinner-Unity#89]
**What is the current behavior?**
Variables read from the yarn project after updating them through the in-memory variable manager show the original value that was declared in the file/yarn project asset. The memory storage debug does show the changed value, and when requested through C#, the value is also correct. The issue only concerns runtime dialogue lines passed to views.

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
I created a [Unity project](https://github.com/Creator13/YarnVariableDemo) as a demonstration. In SampleScene, press S to start the dialogue. On the second line, Jane says how many laps she's walked. The value starts out as 0. After (or during) the conversation, pressing R will increment the number of laps (see console). When the dialogue starts again, it will still display 0 (the starting value) instead of the correctly incremented value. Also note how the debug view of the variable storage shows the incremented value.

**What is the expected behavior?**
The expected behavior is that the variables show the incremented value instead of the original one.

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.0.0-beta4
  - Unity Version: 2021.1.1f1

**Other information** 
I would love to fix it myself but I don't have the time to dive into the entire codebase 😅

**Comment by desplesda** [comment]
Hi there!

First: thank you so much for doing such a fantastic bug report! Having a test project to work with was fantastic, and helped me figure out the problem really quickly.

This is, as far as I can tell, an issue caused by calling `SetValue` with the variable name `laps`, when it should have been `$laps`. When change your code from this:

```csharp
dialogueRunner.variableStorage.SetValue("laps", laps);
```

To this:

```csharp
dialogueRunner.variableStorage.SetValue("$laps", laps);
```

It works as expected.

This is absolutely the fault of Yarn Spinner for not throwing an error, and I've updated `InMemoryVariableStorage` to throw an `ArgumentException` when this happens. This change is in f96cc78.

Thanks again for the amazing bug report!
